
---
# ^ DON'T REMOVE the "---" above!
# ******************************************************************************
# *                          GH-THEMES-MAGIC WEBSITE                           *
# ******************************************************************************
# Customized settings for the gh-themes-magick website.
#
#  -- https://github.com/tajmone/gh-themes-magick
#
# ==============================================================================
#                                 WEBSITE HEADER                                
# ==============================================================================
# These variables are shown in the website header.
# ------------------------------------------------------------------------------
website_title:   'GitHub Pages Themes Magick'
website_tagline:
 - 'Static project website from `README.md` file â€” Published from `master` branch'
# ==============================================================================
#                                  GITHUB LINKS                                 
# ==============================================================================
# The following variables are used for automagically creating links to your repo
# on GitHub, and for the .zip and .tar download links.
# Substitute sample values with your username and repository name as they appear
# on GitHub (CASE SENSITIVE!!!)
# ------------------------------------------------------------------------------
# Example: https://github.com/tajmone/gh-themes-magick
your_github_username: tajmone
your_github_reponame: gh-themes-magick

# ==============================================================================
#                                   HTML META                                   
# ==============================================================================
# HTML Metadata -- for <head> section
# If you don't need a variable, delete its line or comment it out with a `#`!
# ------------------------------------------------------------------------------
title: 'GitHub Pages Themes Magick â€” Turn your README file into a website'
lang:   en
date:   December 16, 2016
author:
  - Tristano Ajmone
description:
  - 'Create your projectsâ€™ website from the README.md file and publish it 
     on GitHub Pages directly from master branch...'
keywords:
  - GitHub Pages
  - website
  - README.md
  - README file
  - repository
  - repo
  - project
  - theme
  - master branch
  - pandoc
  - open source
# ==============================================================================
#                             EXTRA CSS STYLESHEETS                             
# ==============================================================================
# An optional list of extra CSS stylesheets to include from the "/stylesheets/"
# theme's subfolder. Just place your custom stylesheets in that folder and add 
# their filenames to this list.
# DON'T USE ABSOLUTE URLs (ie: "https://" or "http://")!!! If you do it, the
# template will break badly. For includind CSS files with absolute URLs, use the
# "header-includes:" scalar instead (see below).
# ------------------------------------------------------------------------------
css:
  - relative/path/to/extra.css
  - custom.css
# ==============================================================================
#                        CUSTOM HTML TO INJECT IN HEADER                        
# ==============================================================================
# This optional indented block literal scalar can be used to inject (verbatim)
# raw html at the end of the head section, just before the closing </head> tag.
# This can be used to include CSS with absolute URLs, or JavaScript files -- or
# anything you want, without actually editing the template file.
# ------------------------------------------------------------------------------
header-includes:
  - |
    <!-- anything you put here will go verbatim in the header section
         Useful for adding javascripts, custom metadata, and so on... -->
  - |
    <!-- another -->
# ******************************************************************************
# *                             INSERT BEFORE BODY                             *
# ******************************************************************************
# You can inject some extra contents after the opening <body> tag and before the
# contents of your 'README.md' file. It will be parsed as markdown and converted
# to html by pandoc. Use raw html if you need advanced features, but remember
# that all loose text will be enclosed in <p> tags -- wrap it inside a <div> if
# you don't want it parsed as markdown!
# ------------------------------------------------------------------------------
include-before: |
    <div id="starme">
    <iframe style="float:left" src="https://ghbtns.com/github-btn.html?user=tajmone&repo=gh-themes-magick&type=star&count=true&size=large" frameborder="0" scrolling="0" width="160px" height="30px"></iframe>
    <h3>ðŸ¡¸ Give <strong>gh-themes-magick</strong> a star!</h3>
    </div><hr>
# ******************************************************************************
# *                             INSERT AFTER BODY                              *
# ******************************************************************************
# You can also inject extra contents after those of your 'README.md' file and
# before the closing </body> tag. Same rules as for 'include-before' variable.
# ------------------------------------------------------------------------------
include-after: |
    <div id="starmereminder">
    <iframe style="float:left" src="https://ghbtns.com/github-btn.html?user=tajmone&repo=gh-themes-magick&type=star&count=true&size=large" frameborder="0" scrolling="0" width="160px" height="30px"></iframe>
    <h3>ðŸ¡¸ Donâ€™t forget to star <strong>gh-themes-magick</strong>!</h3>
    </div>

# ------------------------------------------------------------------------------
# DON'T REMOVE the "..." below:
...